// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyuwbysahezxobqcnbhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dXdieXNhaGV6eG9icWNuYmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDMzMzcsImV4cCI6MjA3NDMxOTMzN30.vAKxGy4J_57Tc1bsB9ZGtC-uZFk-xWXDAnmLW73qvAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
  },
});